parameters:
    agit.common.cachedir: %kernel.cache_dir%/agit
    agit.common.php.version: ">=5.4.9"
    agit.common.symfony.version: "2.3.*"

services:
    agit.common.cache.persistent:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: [ %agit.common.cachedir% ]

    agit.common.cache.volatile:
        class: Doctrine\Common\Cache\ApcCache

    agit.common.classcollector:
        arguments: [ @kernel ]
        class: Agit\BaseBundle\Service\ClassCollector

    agit.common.filecollector:
        arguments: [ @kernel ]
        class: Agit\BaseBundle\Service\FileCollector

    agit.common.url:
        class: Agit\BaseBundle\Service\UrlService
        arguments: [ %agit.common.domain.app%, %agit.common.domain.cdn%, %agit.common.force.https% ]
