services:

    # main plugin processor service
    agit.pluggable.processor:
        class: Agit\BaseBundle\Service\PluginProcessorService
        arguments: [  @kernel, @annotation_reader, @agit.common.classcollector ]

    agit.pluggable.cache.loader_factory:
        class: Agit\BaseBundle\Pluggable\Cache\CacheLoaderFactory
        arguments: [ @agit.common.cache.persistent ]



    #
    # OBJECT stragety
    #

    agit.pluggable.object.processor_factory:
        private: true
        class: Agit\BaseBundle\Pluggable\Object\ObjectProcessorFactory
        arguments: [ @agit.common.cache.persistent ]
        tags: [{ name: agit.pluggable.processor_factory, type: object }]

    agit.pluggable.object.loader_factory:
        class: Agit\BaseBundle\Pluggable\Object\ObjectLoaderFactory
        arguments: [ @agit.common.cache.persistent, @?service_container ]
