parameters:
    agit.core.cachedir: %kernel.cache_dir%/agit
    agit.core.php.version: ">=5.4.9"
    agit.core.symfony.version: "2.3.*"

services:
    agit.core.cache.persistent:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: [%agit.core.cachedir%]

    agit.core.cache.volatile:
        class: Doctrine\Common\Cache\ApcCache

    agit.core.classcollector:
        arguments: [@kernel]
        class: Agit\CoreBundle\Service\ClassCollector

    agit.core.filecollector:
        arguments: [@kernel]
        class: Agit\CoreBundle\Service\FileCollector

    agit.core.url:
        class: Agit\CoreBundle\Service\UrlService
        arguments: [%agit.core.domain.backend%, %agit.core.domain.frontend%, %agit.core.domain.cdn%, %agit.core.url.force.https%]
