parameters:
    agit.intl.global.catalog.dir: "%kernel.root_dir%/Resources/translations"
    agit.intl.bundle.catalog.dir: "Resources/translations"
    agit.intl.filetypes: { php : php, js : c } # JS files are parsed as C. strange, but works. TODO: recent xgettext versions support JS, check how this works.

services:
    agit.intl.catalog:
        class: Agit\IntlBundle\Service\TranslationCatalogService
        arguments: [@agit.intl.gettext, @agit.core.filecollector, @event_dispatcher, %agit.intl.locales%, %agit.intl.filetypes%, %agit.intl.global.catalog.dir%, %agit.intl.bundle.catalog.dir%]

    agit.intl.gettext:
        public: false
        class: Agit\IntlBundle\Service\GettextService
        arguments: [Resources/data/header.po, Resources/data/plurals.json]

    agit.intl.translate:
        class: Agit\IntlBundle\Service\Translate

    agit.intl.locale:
        class: Agit\IntlBundle\Service\LocaleService
        arguments: [@?agit.intl.localeconfig, %agit.intl.locales%, %agit.intl.global.catalog.dir%, "agit"]

    # Twig extension for template text block translations
    # (optional, no dependency on Twig, as long it's not instantiated)
    agit.intl.twig.translation:
        class: Agit\IntlBundle\Twig\TranslationExtension
        tags: [{ name: twig.extension }]
        arguments: [@agit.intl.translate]
