services:
    agit.validation:
        class: Agit\BaseBundle\Validation\ValidationService
        arguments: [ "@agit.pluggable.object.loader_factory" ]

    agit.validator:
        abstract: true
        class: Agit\BaseBundle\Validation\AbstractValidator
        calls:
            - [ setValidationService, [ "@agit.validation" ] ]

    agit.validator.array:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\ArrayValidator
        tags: [{ name: agit.validator, id: array }]

    agit.validator.boolean:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\BooleanValidator
        tags: [{ name: agit.validator, id: boolean }]

    agit.validator.email:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\EmailValidator
        tags: [{ name: agit.validator, id: email }]

    agit.validator.float:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\FloatValidator
        tags: [{ name: agit.validator, id: float }]

    agit.validator.geolocation:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\GeolocationValidator
        arguments: [ "@agit.validator.array", "@agit.validator.latitude", "@agit.validator.longitude" ]
        tags: [{ name: agit.validator, id: geolocation }]

    agit.validator.integer:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\IntegerValidator
        tags: [{ name: agit.validator, id: integer }]

    agit.validator.latitude:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\LatitudeValidator
        tags: [{ name: agit.validator, id: latitude }]

    agit.validator.longitude:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\LongitudeValidator
        tags: [{ name: agit.validator, id: longitude }]

    agit.validator.multiselection:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\MultiSelectionValidator
        tags: [{ name: agit.validator, id: multiselection }]

    agit.validator.notnull:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\NotNullValidator
        tags: [{ name: agit.validator, id: notnull }]

    agit.validator.notregex:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\NotRegexValidator
        tags: [{ name: agit.validator, id: notregex }]

    agit.validator.null:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\NullValidator
        tags: [{ name: agit.validator, id: null }]

    agit.validator.numeric:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\NumericValidator
        tags: [{ name: agit.validator, id: numeric }]

    agit.validator.object:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\ObjectValidator
        tags: [{ name: agit.validator, id: object }]

    agit.validator.password:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\PasswordValidator
        tags: [{ name: agit.validator, id: password }]

    agit.validator.phonenumber:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\PhoneNumberValidator
        arguments: [ "@agit.validator.regex" ]
        tags: [{ name: agit.validator, id: phonenumber }]

    agit.validator.regex:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\RegexValidator
        tags: [{ name: agit.validator, id: regex }]

    agit.validator.scalar:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\ScalarValidator
        tags: [{ name: agit.validator, id: scalar }]

    agit.validator.selection:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\SelectionValidator
        tags: [{ name: agit.validator, id: selection }]

    agit.validator.string:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\StringValidator
        tags: [{ name: agit.validator, id: string }]

    agit.validator.url:
        parent: agit.validator
        class: Agit\BaseBundle\Validation\UrlValidator
        tags: [{ name: agit.validator, id: url }]
