services:

    agit.validation:
        class: Agit\ValidationBundle\Service\ValidationService
        arguments: [@agit.pluggable.object.loader_factory, @agit.intl.translate, @service_container]
        tags: [{ name: agit.pluggable, type: object, tag: agit.validation, baseClass: Agit\ValidationBundle\Plugin\AbstractValidator }]
