services:
    agit.intl.locale:
        class: Agit\IntlBundle\Service\LocaleService
        arguments: [@?agit.intl.localeconfig, %agit.intl.locales%, %agit.intl.global.catalog.dir%, "agit"]

    # reusable event listener for the agit.intl.files.cleanup event
    agit.intl.listener.files.cleanup:
        abstract: true
        class: Agit\IntlBundle\EventListener\BundleFilesCleanupListener
        arguments: [ @filesystem ]

    # one-time cleanup event listener for agit.intl.catalog.cleanup
    agit.intl.listener.catalog.cleanup:
        class: Agit\IntlBundle\EventListener\CatalogCleanupListener
        arguments: [ @filesystem ]
        tags: [{ name: kernel.event_listener, event: agit.intl.catalog.cleanup, method: onRegistration }]

    # (Optional) Twig extension for template text block translations
    agit.intl.twig.translation:
        class: Agit\IntlBundle\Twig\TranslationExtension
        arguments: [ "@agit.intl.locale" ]
        tags: [{ name: twig.extension }]

    # checks if a bundle has Twig templates, and prepares them for extraction
    agit.intl.bundle.twig.collect:
        class: Agit\IntlBundle\EventListener\BundleTwigFilesListener
        arguments: [ @agit.common.filecollector, @twig ]
        tags: [{ name: kernel.event_listener, event: agit.intl.files.register, method: onRegistration }]

    # cleans up temporary files
    agit.intl.bundle.twig.cleanup:
        parent: agit.intl.listener.files.cleanup
        tags: [{ name: kernel.event_listener, event: agit.intl.files.cleanup, method: onRegistration }]
