services:

    # main plugin processor service
    agit.pluggable.processor:
        class: Agit\PluggableBundle\Service\ProcessorService
        arguments: [  @kernel, @annotation_reader, @agit.common.classcollector ]


    #
    # CACHE stragety
    #

    agit.pluggable.cache.processor_factory:
        private: true
        class: Agit\PluggableBundle\Strategy\Cache\CacheProcessorFactory
        arguments: [ @agit.common.cache.persistent, @?service_container ]
        tags: [{ name: agit.pluggable.processor_factory, type: cache }]

    agit.pluggable.cache.loader_factory:
        class: Agit\PluggableBundle\Strategy\Cache\CacheLoaderFactory
        arguments: [ @agit.common.cache.persistent ]



    #
    # OBJECT stragety
    #

    agit.pluggable.object.processor_factory:
        private: true
        class: Agit\PluggableBundle\Strategy\Object\ObjectProcessorFactory
        arguments: [ @agit.common.cache.persistent ]
        tags: [{ name: agit.pluggable.processor_factory, type: object }]

    agit.pluggable.object.loader_factory:
        class: Agit\PluggableBundle\Strategy\Object\ObjectLoaderFactory
        arguments: [ @agit.common.cache.persistent, @?service_container ]



    #
    # SEED stragety
    #

    agit.pluggable.seed.processor_factory:
        private: true
        class: Agit\PluggableBundle\Strategy\Seed\SeedProcessorFactory
        arguments: [ @doctrine.orm.entity_manager, @?service_container ]
        tags: [{ name: agit.pluggable.processor_factory, type: seed }]

    # dummy pluggable service, only there for seeds to be registered
    agit.pluggable.seed:
        class: Agit\PluggableBundle\Strategy\Seed\SeedService
        tags: [{ name: agit.pluggable, type: seed }]



    #
    # ENTITY stragety
    #

    agit.pluggable.entity.processor_factory:
        private: true
        class: Agit\PluggableBundle\Strategy\Entity\EntityProcessorFactory
        arguments: [ @agit.pluggable.object.processor_factory, @agit.pluggable.seed.processor_factory, @?service_container ]
        tags: [{ name: agit.pluggable.processor_factory, type: entity }]

    agit.pluggable.entity.loader_factory:
        class: Agit\PluggableBundle\Strategy\Entity\EntityLoaderFactory
        arguments: [ @agit.common.cache.persistent, @doctrine.orm.entity_manager, @?service_container ]
